/*
 * Flash Loader with Position Independent Code (PIC) Demo
 * Main program runs in SRAM1, loads and executes flash ops in SRAM0
 * 
 * Architecture:
 *   SRAM1 (0x20000000): Main control program
 *   SRAM0 (0x1FFF0000): Dynamically loaded flash operation functions
 * 
 * Based on OpenOCD STMQSPI flash loader concept
 */

#include "s300.h"
#include <stdio.h>
#include <string.h>
#include <stdint.h>

#include "rcc.h"
#include "gpio.h"
#include "uart.h"
#include "board.h"
#include "qspi_cadence.h"

/* Memory regions */
#define SRAM0_BASE      0x1FFF0000u
#define SRAM0_SIZE      (192 * 1024u)
#define SRAM1_BASE      0x20000000u
#define SRAM1_SIZE      (64 * 1024u)

/* Flash operation function signatures */
typedef int (*flash_read_fn_t)(uint32_t addr, uint8_t *buf, uint32_t len, uint32_t qspi_base);
typedef int (*flash_write_fn_t)(uint32_t addr, const uint8_t *buf, uint32_t len, uint32_t qspi_base);
typedef int (*flash_erase_fn_t)(uint32_t addr, uint32_t type, uint32_t qspi_base);
typedef uint32_t (*crc32_fn_t)(const uint8_t *data, uint32_t len);

/* Include the auto-generated flash_ops.inc */
/* This is generated by: make flash_ops.inc */
/* For now, we'll use a placeholder structure */

static const uint8_t flash_ops_code[] = {
    /* This will be populated by build system from flash_ops.bin */
    /* Placeholder - real code will be inserted by Makefile */
    0x00, 0x00, 0x00, 0x00
};

#define FLASH_OPS_SIZE  sizeof(flash_ops_code)

/* Control structure in SRAM1 */
typedef struct {
    uint32_t sram0_load_addr;       /* Where we load code in SRAM0 */
    flash_read_fn_t read_fn;
    flash_write_fn_t write_fn;
    flash_erase_fn_t erase_fn;
    crc32_fn_t crc32_fn;
    uint32_t qspi_base;
} flash_loader_ctx_t;

static flash_loader_ctx_t g_ctx;

/* Load flash ops code into SRAM0 and resolve function pointers */
static int flash_loader_init(void)
{
    printf("[LOADER] Initializing Flash Loader (PIC)\r\n");
    printf("[LOADER] SRAM0: 0x%08lX, size: %lu bytes\r\n", 
           (unsigned long)SRAM0_BASE, (unsigned long)SRAM0_SIZE);
    printf("[LOADER] SRAM1: 0x%08lX, size: %lu bytes\r\n",
           (unsigned long)SRAM1_BASE, (unsigned long)SRAM1_SIZE);
    
    /* Choose load address in SRAM0 (aligned) */
    g_ctx.sram0_load_addr = SRAM0_BASE + 0x1000;  /* Leave some space */
    
    /* Check if flash_ops code fits */
    if (FLASH_OPS_SIZE > SRAM0_SIZE - 0x1000) {
        printf("[LOADER] ERROR: flash_ops code too large (%lu bytes)\r\n",
               (unsigned long)FLASH_OPS_SIZE);
        return -1;
    }
    
    printf("[LOADER] Loading flash_ops to 0x%08lX (%lu bytes)\r\n",
           (unsigned long)g_ctx.sram0_load_addr, (unsigned long)FLASH_OPS_SIZE);
    
    /* Copy flash_ops code to SRAM0 */
    memcpy((void *)g_ctx.sram0_load_addr, flash_ops_code, FLASH_OPS_SIZE);
    
    /* Resolve function pointers (offset from load address) */
    /* In PIC code, we need to get the function table first */
    typedef uint32_t* (*get_table_fn_t)(void);
    get_table_fn_t get_table = (get_table_fn_t)(g_ctx.sram0_load_addr | 1); /* Thumb bit */
    
    /* For now, use fixed offsets (this should match flash_ops.S layout) */
    /* Real implementation would parse the function table */
    g_ctx.read_fn = (flash_read_fn_t)((g_ctx.sram0_load_addr + 0x00) | 1);
    g_ctx.write_fn = (flash_write_fn_t)((g_ctx.sram0_load_addr + 0x40) | 1);
    g_ctx.erase_fn = (flash_erase_fn_t)((g_ctx.sram0_load_addr + 0xC0) | 1);
    g_ctx.crc32_fn = (crc32_fn_t)((g_ctx.sram0_load_addr + 0x100) | 1);
    
    g_ctx.qspi_base = g_qspi.reg_base;
    
    printf("[LOADER] Function pointers:\r\n");
    printf("  read:  0x%08lX\r\n", (unsigned long)g_ctx.read_fn);
    printf("  write: 0x%08lX\r\n", (unsigned long)g_ctx.write_fn);
    printf("  erase: 0x%08lX\r\n", (unsigned long)g_ctx.erase_fn);
    printf("  crc32: 0x%08lX\r\n", (unsigned long)g_ctx.crc32_fn);
    
    /* Flush instruction cache if applicable */
    __DSB();
    __ISB();
    
    printf("[LOADER] Init complete\r\n");
    return 0;
}

/* Test flash operations using PIC code in SRAM0 */
static int flash_loader_test(void)
{
    uint8_t buf[256];
    int rc;
    
    printf("\r\n[TEST] Starting flash operation tests\r\n");
    
    /* Test 1: Read from flash */
    printf("[TEST] 1. Read 256 bytes from flash @ 0x100000\r\n");
    memset(buf, 0, sizeof(buf));
    
    rc = g_ctx.read_fn(0x100000, buf, 256, g_ctx.qspi_base);
    printf("[TEST] Read result: %d\r\n", rc);
    
    if (rc == 0) {
        printf("[TEST] First 32 bytes: ");
        for (int i = 0; i < 32; i++) {
            printf("%02X ", buf[i]);
        }
        printf("\r\n");
    }
    
    /* Test 2: Calculate CRC32 */
    printf("[TEST] 2. Calculate CRC32 of read data\r\n");
    uint32_t crc = g_ctx.crc32_fn(buf, 256);
    printf("[TEST] CRC32: 0x%08lX\r\n", (unsigned long)crc);
    
    /* Test 3: Write test (commented out for safety) */
    /*
    printf("[TEST] 3. Write test pattern\r\n");
    for (int i = 0; i < 256; i++) {
        buf[i] = (uint8_t)(i ^ 0xAA);
    }
    rc = g_ctx.write_fn(0x100000, buf, 256, g_ctx.qspi_base);
    printf("[TEST] Write result: %d\r\n", rc);
    */
    
    /* Test 4: Erase test (commented out for safety) */
    /*
    printf("[TEST] 4. Erase 4KB sector\r\n");
    rc = g_ctx.erase_fn(0x100000, 0, g_ctx.qspi_base);
    printf("[TEST] Erase result: %d\r\n", rc);
    */
    
    printf("[TEST] Tests complete\r\n");
    return 0;
}

int main(void)
{
    board_init();
    
    uint32_t ahb_hz = rcc_get_clock(RCC_CLOCK_AHB);
    uint32_t sclk_hz = ahb_hz / 2u;
    
    printf("\r\n");
    printf("============================================\r\n");
    printf(" S300 Flash Loader - Position Independent  \r\n");
    printf("   Based on OpenOCD STMQSPI Architecture   \r\n");
    printf("============================================\r\n");
    printf("AHB Clock:  %lu Hz\r\n", (unsigned long)ahb_hz);
    printf("QSPI Clock: %lu Hz\r\n", (unsigned long)sclk_hz);
    printf("\r\n");
    
    /* Initialize QSPI controller */
    qspi_set_verbose(false);
    qspi_cadence_init(ahb_hz, sclk_hz);
    
    /* Initialize flash loader */
    if (flash_loader_init() != 0) {
        printf("[MAIN] Flash loader init failed\r\n");
        return -1;
    }
    
    /* Run tests */
    flash_loader_test();
    
    /* Interactive command loop */
    printf("\r\n[MAIN] Entering command loop\r\n");
    printf("Commands:\r\n");
    printf("  read ADDR LEN  - Read from flash\r\n");
    printf("  info           - Show loader info\r\n");
    printf("  help           - Show this help\r\n");
    
    char line[128];
    while (1) {
        printf("\r\n> ");
        
        /* Simple command input (blocking) */
        int n = 0;
        while (n < sizeof(line) - 1) {
            uint16_t ch = uart_read(UART_IDX3, UARTTYPE_STD_SERIAL);
            char c = (char)(ch & 0xFF);
            if (c == '\r') continue;
            if (c == '\n') break;
            line[n++] = c;
        }
        line[n] = '\0';
        
        if (strcmp(line, "info") == 0) {
            printf("Flash Loader Info:\r\n");
            printf("  SRAM0 Load: 0x%08lX\r\n", (unsigned long)g_ctx.sram0_load_addr);
            printf("  Code Size:  %lu bytes\r\n", (unsigned long)FLASH_OPS_SIZE);
            printf("  QSPI Base:  0x%08lX\r\n", (unsigned long)g_ctx.qspi_base);
        } else if (strcmp(line, "help") == 0) {
            printf("Commands:\r\n");
            printf("  read ADDR LEN  - Read from flash\r\n");
            printf("  info           - Show loader info\r\n");
            printf("  help           - Show this help\r\n");
        } else if (strncmp(line, "read ", 5) == 0) {
            unsigned long addr = 0, len = 0;
            if (sscanf(line + 5, "%lx %lu", &addr, &len) == 2) {
                if (len > 256) len = 256;
                uint8_t buf[256];
                int rc = g_ctx.read_fn((uint32_t)addr, buf, (uint32_t)len, g_ctx.qspi_base);
                printf("Read result: %d\r\n", rc);
                if (rc == 0) {
                    for (uint32_t i = 0; i < len; i++) {
                        if (i % 16 == 0) printf("\r\n%08lX: ", (unsigned long)(addr + i));
                        printf("%02X ", buf[i]);
                    }
                    printf("\r\n");
                }
            } else {
                printf("Usage: read ADDR LEN\r\n");
            }
        } else if (n > 0) {
            printf("Unknown command: %s\r\n", line);
        }
    }
    
    return 0;
}
